name: Lint
on:
  pull_request:
    paths:
      - ".eslint*"
      - .prettier*"
      - "**/*.js"
      - "**/*.md"
      - "**/*.json"
      - "**/*.yml"
      - "**/*.yaml"
  push:
    paths:
      - ".eslint*"
      - .prettier*"
      - "**/*.js"
      - "**/*.md"
      - "**/*.json"
      - "**/*.yml"
      - "**/*.yaml"
    branches-ignore:
      - "dependabot/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.2.0
      - run: yarn
      - run: yarn run lint-ci
